# Generated by Django 3.1.2 on 2020-10-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionset',
            name='is_answer',
        ),
    ]
