# Generated by Django 3.1.2 on 2020-10-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_optionset_is_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionset',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_option_set', to='api.questionset'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_set', to='api.examination'),
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='questions',
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_set', to='api.question'),
        ),
    ]
