# Generated by Django 3.1.2 on 2020-10-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201025_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='set',
        ),
        migrations.CreateModel(
            name='ExaminationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField()),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_set', to='api.examination')),
            ],
        ),
        migrations.AlterField(
            model_name='questionset',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_set_set', to='api.examinationset'),
        ),
    ]
