# Generated by Django 3.1.2 on 2020-10-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201025_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='examination',
            new_name='examination_set',
        ),
    ]
